let allMusic = [
  {
    name: "Banjaara-Ek Villain",
    artist: "Mohammed Irfan",
    img: "banjara",
    src: "banjara",
  },
  {
    name: "Ae Dil Hai Mushki",
    artist: "Pritam & Arijit Singh",
    img: "adil_muskil",
    src: "adil_muskil",
  },
  {
    name: "Bawara Mann-Jolly LL.B 2 ",
    artist: "Jubin Nautiyal & Neeti Mohan",
    img: "bawra_man",
    src: "bawra_man",
  },
  {
    name: "Cry For Me",
    artist: "The Weeknd",
    img: "cry_forme",
    src: "cry_forme",
  },
  {
    name: "Dekhte Dekhte",
    artist: "Atif Aslam & Nusrat Fateh Ali Khan ",
    img: "dekhte_dekhte",
    src: "dekhte_dekhte",
  },
  {
    name: "Dil Diyan Gallan-Tiger Zinda Hai",
    artist: "Atif Aslam, Vishal & Shekhar,",
    img: "dil_diya",
    src: "dil_diya",
  },
  {
    name: "Jhol-Coke Studio ",
    artist: "Annural Khalid & Maanu",
    img: "jhol",
    src: "jhol",
  },
  {
    name: "Jo Tere Sang-Blood Money",
    artist: "Mustafa Zahid & Jeet Gannguli",
    img: "jo_teresang",
    src: "jo_teresang",
  },
  {
    name: "Jo Tum Mere Ho ",
    artist: "Anuv Jain",
    img: "jotum_mere",
    src: "jotum_mere",
  },
  {
    name: "Kabhi Kabhi Aditi ",
    artist: "Rashid Ali",
    img: "kabhi_kabhi",
    src: "kabhi_kabhi",
  },
  {
    name: "Why This Kolaveri Di",
    artist: "Dhanush",
    img: "kolaveri",
    src: "kolaveri",
  },
  {
    name: "Kothin",
    artist: "Arijit Singh",
    img: "kothin",
    src: "kothin",
  },
  {
    name: "MENTE MA ",
    artist: "Mc Staff & Nakama",
    img: "mente_ma",
    src: "mente_ma",
  },
  {
    name: "Paaro",
    artist: "Aditya Rikhari",
    img: "paaro",
    src: "paaro",
  },
  {
    name: "Afusic-Pal Pal ",
    artist: "Talwiinder",
    img: "pal_pal",
    src: "pal_pal",
  },
  {
    name: "Siraa",
    artist: "Guru Randhawa & Manpreet Mann",
    img: "sirra",
    src: "sirra",
  },
  {
    name: "Sun Raha hai-Aashiqui 2 ",
    artist: "Ankit Tiwari & Shreya Ghoshal",
    img: "sun_raha",
    src: "sun_raha",
  },
  {
    name: "Take Olpo Kache Dakchi",
    artist: "Mahtim Shakib",
    img: "take_olpo",
    src: "take_olpo",
  },
  {
    name: "Tera Ghata",
    artist: "Gajendra verma",
    img: "tera_ghata",
    src: "tera_ghata",
  },
  {
    name: "YO ME SIENTO LIBRE",
    artist: "FAZ, Gang & Hayasa",
    img: "yome_sento",
    src: "yome_sento",
  },
];
